config/routes.rb
Devsphere::Application.routes.draw do
  devise_for :users
  resources :posts

  get '/talk/users/:id/profile' => 'talk#user_profile', :as => :talk_user_profile
  get '/talk/threads/:id' => 'talk#single_thread', :as => :talk_thread
  get '/talk/post/:id' => 'talk#permalink', :as => :talk_permalink
  get '/talk/file_db' => 'talk#file_database', :as => :file_db
  get '/talk/live_update' => 'talk#live_update', :as => :live_update
  
  root :to => "talk#index"

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  CATEGORIES = ["Audio", "Video", "Image", "Script", "Document", "Other"]
  attr_accessible :file, :post_id, :category
  belongs_to :post
  belongs_to :user
  validates :file, :presence => true
  validates :category, :inclusion => { :in => CATEGORIES }
  mount_uploader :file, FileUploader
  self.per_page = 30
  

  def self.new_to_old
    order("created_at DESC")
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  self.per_page = 15
  DEPTH_LIMIT = 1 # How deep replies can nest
  belongs_to :user
  belongs_to :post
  has_many :attachments, :dependent => :destroy
  has_many :posts, :foreign_key => :parent_id, :dependent=>:destroy
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings
  
  validates :body, :presence => true, :length=>{:minimum=>1}
  validates :user_id, :presence => true
  
  accepts_nested_attributes_for :attachments,
    :reject_if=>lambda { |a| a[:file].blank? },
    :allow_destroy=>true

  before_save :process_body
  after_create :send_notification_email

  def self.threads
    # Only get the top level posts
    where("parent_id IS NULL").order("updated_at DESC")
  end

  def top_level
    # Return thread starter
    current_post = self
    while !current_post.top_level?
      current_post = current_post.parent
    end
    current_post
  end
 
  def top_level?
    self.parent_id ? false : true
  end

  def parent
    Post.find self.parent_id
  end 

  def replies
    self.posts
  end

  private
  def process_body
    regex = Regexp.new '((https?:\/\/|www\.)([-\w\.]+)+(:\d+)?(\/([\w\/_\.]*(\?\S+)?)?)?)'
    self.body.gsub!( regex, '<a href="\1">\1</a>' )
    self.body = strip_bad_tags(self.body)
  end

  def strip_bad_tags(s)
    # converting newlines 
    s.gsub!(/\r\n?/, "\n") 
 
    # escaping HTML to entities 
    s = s.to_s.gsub('&', '&amp;').gsub('<', '&lt;').gsub('>', '&gt;') 
 
    # blockquote tag support 
    s.gsub!(/\n?&lt;blockquote&gt;\n*(.+?)\n*&lt;\/blockquote&gt;/im, "<blockquote>\\1</blockquote>") 
 
    # other tags: b, i, em, strong, u 
    %w(b i em strong u).each { |x|
         s.gsub!(Regexp.new('&lt;(' + x + ')&gt;(.+?)&lt;/('+x+')&gt;',
                 Regexp::MULTILINE|Regexp::IGNORECASE), 
                 "<\\1>\\2</\\1>") 
        } 
 
    # A tag support 
    # href="" attribute auto-adds http:// 
    s = s.gsub(/&lt;a.+?href\s*=\s*['"](.+?)["'].*?&gt;(.+?)&lt;\/a&gt;/im) { |x|
            '<a href="' + ($1.index('://') ? $1 : 'http://'+$1) + "\">" + $2 + "</a>" 
          } 
 
    # replacing newlines to <br> ans <p> tags 
    # wrapping text into paragraph 
    s = "<p>" + s.gsub(/\n\n+/, "</p>\n\n<p>").
            gsub(/([^\n]\n)(?=[^\n])/, '\1<br />') + "</p>" 
 
    s    
  end 

  def send_notification_email
    UserMailer.notification_email(self).deliver
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, :dependent => :destroy
  has_many :posts, :through => :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  ADMINS = ["keyvanfatehi@gmail.com"]
  has_many :posts
  has_many :attachments
  validates :nickname, :presence=>true, :uniqueness=>true
  validates :email, :uniqueness=>true
  validates :password, :length=>{:minimum=>3}
# Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :nickname, :email, :password, :password_confirmation, :remember_me
  attr_protected :is_admin, :points
  
  before_create :initial_setup
  after_create :send_welcome_email

  def ascii_only?
    false
  end

  def self.online_users
    time_range = 30.seconds.ago..Time.now
    where(:last_request_at=>time_range).all.map {|u| u.nickname }
  end

  def gravatar
    "http://www.gravatar.com/avatar.php?gravatar_id=#{Digest::MD5.hexdigest self.email}&default=identicon"
  end
  
  def give_points_for(post)
    points = self.points + post.attachments.count + 1
    self.update_column(:points, points)
  end

  def admin?
    self.is_admin
  end

  def admin!
    self.update_column(:is_admin, true)
  end

  def unadmin!
    self.update_column(:is_admin, false)
  end

  def initial_setup
    self.is_admin = ADMINS.include?(self.email)
    self.points = 0
  end
  
  def send_welcome_email
    UserMailer.welcome_email(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def set_last_request_at 
    current_user.update_column(:last_request_at, Time.now) if user_signed_in? 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :only=>[:create]
  before_filter :set_last_request_at
  
  def create
    post = current_user.posts.new(params[:post])
    if post.save
      current_user.give_points_for(post)
      flash[:notice] = "Thanks for contributing!"
    else
      flash[:alert] = %{
        There was a problem creating your post.<br><b>
        #{post.errors.full_messages.join('<br>')}</b>
      }.html_safe
      session[:body_saver] = post.body  
    end
    redirect_to :back
  end
end

app/controllers/talk_controller.rb
class TalkController < ApplicationController
  before_filter :prepare_objects
  before_filter :set_last_request_at

  def index
    @posts = Post.threads.page(params[:page])
    @files = Attachment.new_to_old.limit(30)
  end

  def file_database
    @files = Attachment.new_to_old.page(params[:page])
  end

  def user_profile
    @user = User.find params[:id]
    @posts = @user.posts
  end

  def single_thread
    @post = Post.find(params[:id]).top_level
  end

  def permalink
    @post = Post.find(params[:id])
    render :single_thread if @post.top_level?
  end
  
  def live_update
    # 1 : indicates the presence of user on the website (for online status display)
    # 2 : if any updates have occured on the page
      # a : if a user goes offline 
    @user = current_user
    @online_users = User.online_users
  end

  private
  def prepare_objects
    @new_post = Post.new
    @new_post.attachments.build
    if @body_saver = session[:body_saver]
      session[:body_saver] = nil
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def talk_links
    links = (current_page?(root_url) ? {} : {"Index"=>root_url})
    links.merge({
      "Cry.li Home"=>"http://cry.li/",
      "Git (1)"=>"http://cry.li/files/knowledge/git_setup/",
      "Git (2)"=>"http://cry.li/files/knowledge/git_setup/part_2.html",
      "Crydev SDK"=>"http://freesdk.crydev.net/",
      "Lua Docs" => "http://www.lua.org/manual/5.1/"
    })
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/talk_helper.rb
module TalkHelper
  def custom_time(t)
    t.strftime('%H:%M UTC') + t.strftime("%z").gsub('0','')
  end

  def link_to_new_post(text, opts={})
    render :partial => 'new_post', :locals=>{ :link_text=>text,
                                              :parent=>opts[:parent],
                                              :link_class=>opts[:class]}
  end

  def can_nest?(depth)
    depth < Post::DEPTH_LIMIT
  end

  def render_post(post, opts={})
    if opts[:only_post]
      locals = {:post=>post, :depth=>nil, :only_post=>true}
    else
      depth = (opts[:depth].nil? ? 0 : opts[:depth]+1)
      locals = {:post=>post, :depth=>depth, :only_post=>false}
    end
    render :partial => 'post', :locals=>locals
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devsphere</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if notice.present? %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert"><%= alert %></p>
  <% end %>
    
<%= yield %>

</body>
</html>

app/views/layouts/talk.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devsphere::Talk</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if notice.present? %>
    <p class="flash notice"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="flash alert"><%= alert %></p>
  <% end %>
  <% if @body_saver.present? %>
    <div class="body_saver">
      <p class="blurb">For your convenience, your text is below:</p>
      <p><%= @body_saver %></p>
    </div>
  <% end %>

  <div id="talkwrapper">
    <div id="rightcol">
      <%= custom_time Time.now %>
      <% unless user_signed_in? %>
        <p class="alert">You must be logged in to post or view file attachments</p>
      <% end %>
      <%= render :partial=>"user_nav" %>
      <%= render :partial=>"file_list" if user_signed_in? && @files.present? %>
    </div>
    <div id="content">
      <div id="links">
        <% talk_links.each do |k,v| %>
          <%= link_to k, v %>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/talk/_file_list.html.erb
<% unless current_page? file_db_path %>
<ul class="file_list">
  <%= link_to "Jump to File DB", file_db_path %>
  <% @files.each do |f| %>
    <li>
      <%= link_to f.post.user.nickname, talk_user_profile_path(f.post.user), :class=>:graylink %> (<%= f.post.user.points %>)
      <%= link_to "uploaded", talk_permalink_path(f.post), :class=>:graylink %>
      <br>
      <%= link_to f.file_identifier, f.file_url, :class=>'file' %>
      <br>
      <%= time_ago_in_words f.created_at %> ago
    </li>
  <% end %>
  <%= link_to "Jump to File DB", file_db_path %>
</ul>
<% end %>

app/views/talk/_new_post.html.erb
<%= link_to link_text, "#", :class=>"shytoggle #{link_class}" %>
<div class="shybox new_post" style="display:none">
  <%= form_for @new_post, :html => {:multipart => true} do |f| %>
    <%= f.hidden_field :parent_id, :value=>parent.id if parent.present? %>
    <%= f.text_area :body %><br>

    <div class="actions">
      <%= button_tag "Attach Another File", :class=>"add_attachment" %>
      <div class="attachment_fields">
        <%= f.fields_for :attachments do |a| %>
          <%= a.label :file, "File: " %>
          <%= a.file_field :file %>
          <%= a.label :category, "Category: " %>
          <%= a.select :category, Attachment::CATEGORIES, {:include_blank => true} %>
          <%= button_tag "Clear", :class=>"remove_attachment" %>
        <% end %>
      </div>
      <%= submit_tag "Submit", :class=>"finish" %>
      <%= button_tag "Cancel", :class=>"hide_parent finish" %>
    </div>  
  <% end %>
</div>

app/views/talk/_post.html.erb
<div class="post">
  <%= image_tag post.user.gravatar, :class=>"avatar" %>

  <div class="top_bar">
    <%= link_to '[-]', '#', :class=>"expand" %>
    <div class="info_block">
      <span class="time"><%= time_ago_in_words post.created_at %> ago</span><br>
      <%= link_to "permalink", talk_permalink_path(post) %>
    </div>
    <div class="author_block">
      <%= link_to post.user.nickname, talk_user_profile_path(post.user), :class=>"author" %>  
      (<%= post.user.points %>)<br>
      <div class="presence"></div>
    </div>
  </div>

  <div class="expandable">

  <div class="body"><%= post.body.html_safe %></div>

  <% if user_signed_in? && (attachments = post.attachments) && attachments.any? %>
    <div class="attachments">
      <% attachments.each do |a| %>
        <%= link_to a.file_identifier, a.file_url, :class=>"file" %>
      <% end %>
    </div>
  <% end %>


  <% if !only_post && (replies = post.replies) %>
    <div class="replies">
      <% replies.each do |reply| %>
        <%= render_post reply, :depth=>depth %>
      <% end %>
    </div>
  <% end %>

    <div class="bottom_bar">
      <%#= link_to "parent", '#', :class=>"jump_to_parent" unless post.top_level? %>
      <% if only_post || current_page?(talk_permalink_path(post)) %>
        <%= link_to "jump to thread", talk_thread_path(post) %>
      <% else %>
        <% if user_signed_in? %>
          <%= link_to_new_post("reply", :parent=>post) if can_nest?(depth) %>
          <%= %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/talk/_user_nav.html.erb
<div id="usernav">
	<center><b>Teamspeak 3 server: cry.li</b></center>
  <% if current_user %>
    <%= image_tag current_user.gravatar, :class=>"avatar" %>
    <%= link_to "Logout", "users/sign_out", :method=>:delete %><br><br>
    Welcome back, <%= link_to current_user.nickname, talk_user_profile_path(current_user) %>!
  <% else %>
    <%= form_for :user, :url=>user_session_path do |f| %>
      <p><%= f.label :email %><br><%=
		# if (current_user) <-- lol, started, coding c style... this is ruby, u can drop 1-liners:
		f.text_field :email if user_signed_in?
%></p>
      <p><%= f.label :password %><br><%= f.password_field :password %></p>
      <%= f.submit "Login" %><br><%= link_to "Register", new_user_registration_path %>
    <% end %>
  <% end %>
</div>

app/views/talk/file_database.html.erb
<table class="file_list file_db">
  <tr>
    <th>Nick</th>
    <th>File</th>
    <th>Kind</th>
    <th>Post</th>
    <th>Date</th>
  <tr>
<% @files.each do |f| %>
  <tr class="<%= cycle('even', 'odd') %>">
    <td><%= link_to f.post.user.nickname+" (#{f.post.user.points})", talk_user_profile_path(f.post.user), :class=>:graylink %></td>
    <td><%= link_to f.file_identifier, f.file_url, :class=>'file' %></td>
    <td><%= f.category %></td>
    <td><%= link_to "link", talk_permalink_path(f.post), :class=>:graylink %></td>
    <td><%= f.created_at.strftime("%D") %></td>
  <tr>
  <% end %>
</table>

app/views/talk/index.html.erb
<div id="search">
  <%= text_field_tag :search, "Not yet implemented", :style=>"color:#aaa" %>
  <%= button_tag "Search" %>
</div>
<div id="posts">
  <%= link_to_new_post("New Thread", :class=>"silver_button new_thread") if user_signed_in? %>
  <%= will_paginate @posts %>
  <% @posts.each do |post| %>
    <%= render_post post %>
  <% end %>
  <%= will_paginate @posts %>
  <center><%= link_to "Return to top", "#" %></center>
</div>

app/views/talk/live_update.js.erb
// Update user statuses

var online_users = [<%= @online_users.map{|u| "'#{u}'"}.join(',') %>];
$('.author_block').each(function (i, e) {
  var user = $(e).children('a.author').text();
  if ($.inArray(user, online_users) == -1 ) { // user not online
    $(e).children('.presence').text('Offline');
  } else 
    $(e).children('.presence').text('Online');
});

// FIXME implement post insertion 

app/views/talk/permalink.html.erb
<div id="posts">
  <%= render_post @post %>
</div>

app/views/talk/single_thread.html.erb
<h1>Viewing full thread</h1>
<div id="posts">
  <div class="top_level">
    <%= render_post @post %>
  </div>
  <center><%= link_to "Return to top", "#" %></center>
</div>

app/views/talk/user_profile.html.erb
<h1><%= @user.nickname %>'s profile</h1>
<div id="posts">
  <% @posts.each do |post| %>
    <div class="post">
      <%= render_post post, :only_post=>true %>
    </div>
  <% end %>
  <center><%= link_to "Return to top", "#" %></center>
</div>